spring.datasource.url=jdbc:sqlserver://sqlsrv-mockdata.database.windows.net:1433;database=mockdata-dev;encrypt=true;trustServerCertificate=false;loginTimeout=30;Authentication=ActiveDirectoryServicePrincipal
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=${AZURE_CLIENT_ID}
spring.datasource.password=${AZURE_CLIENT_SECRET}
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.h2.console.enabled=false
spring.jpa.properties.hibernate.default_schema=dbo
